timeout: 3

wallpaper: boot():/boot/logo.bmp
wallpaper_style: centered
backdrop: 0a0a0a

/Anvil OS
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/init_srvs.cpio
    module_cmdline: init_srvs